    name: Simple Test Workflow

    on:
      push:
        branches:
          - main # Se ejecutará cada vez que haya un push a main

    jobs:
      test_job:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v4
          - name: Print a message
            run: echo "Hello, Matías! This workflow is running."
          - name: List files
            run: ls -la
    